---
title: "HW3_Part2"
output: html_document
---
#探討PTT高中板

###前言:
###本人為學測順利申請升上大學的準大一生，然某些同學們仍為自己的目標努力奮戰至7月初，放榜日為8/7，因而好奇今年指考成績公布前一天(7/18)至公布後一天(7/20)的心情與討論狀況，了解年輕鄉民們的考試結果為何

-------------------------------------------------------------------------------------------------

## Loading Packages
```{r}
library(bitops)
library(httr)
library(XML)
library(RCurl)
library(tm)
library(NLP)
library(tmcn)
library(jiebaRD)
library(jiebaR)
library(Matrix)
library(ggplot2)
library(varhandle)
library(knitr)
library(factoextra)
```

## Text Mining
```{r}
from <- 2418 # 2018-07-18
to   <- 2430 # 2018-07-20
prefix = "https://www.ptt.cc/bbs/SENIORHIGH/index"

data <- list()
for( id in c(from:to) )
{
  url  <- paste0( prefix, as.character(id), ".html" )
  html <- htmlParse( GET(url) )
  url.list <- xpathSApply( html, "//div[@class='title']/a[@href]", xmlAttrs )
  data <- rbind( data, as.matrix(paste('https://www.ptt.cc', url.list, sep='')) )
}
data <- unlist(data)

head(data)
```

-------------------------------------------------------------------------------------------------

## Setting the Date (Mually)
#####註:手動將相同日期的貼文集合在一個txt

-------------------------------------------------------------------------------------------------

## Cleaning
```{r}
d.corpus <- Corpus( DirSource("./DATA") )
d.corpus <- tm_map(d.corpus, removePunctuation)
d.corpus <- tm_map(d.corpus, removeNumbers)
d.corpus <- tm_map(d.corpus, function(word) {
    gsub("[A-Za-z0-9]", "", word)
})
```

-------------------------------------------------------------------------------------------------

## Segment
```{r}
mixseg = worker()
jieba_tokenizer = function(d)
{
  unlist( segment(d[[1]], mixseg) )
}
seg = lapply(d.corpus, jieba_tokenizer)

count_token = function(d)
{
  as.data.frame(table(d))
}
tokens = lapply(seg, count_token)

n = length(seg)
TDM = tokens[[1]]
colNames <- names(seg)
colNames <- gsub(".txt", "", colNames)
for( id in c(2:n) )
{
  TDM = merge(TDM, tokens[[id]], by="d", all = TRUE)
  names(TDM) = c('d', colNames[1:id])
}
TDM[is.na(TDM)] <- 0

kable(head(TDM))
kable(tail(TDM))
```

-------------------------------------------------------------------------------------------------

## TFIDF and Matrix
```{r}
tf <- apply(as.matrix(TDM[,2:(n+1)]), 2, sum)


idfCal <- function(word_doc)
{ 
  log2( n / nnzero(word_doc) ) 
}
idf <- apply(as.matrix(TDM[,2:(n+1)]), 1, idfCal)

doc.tfidf <- TDM
# for(x in 1:nrow(TDM))
# {
#   for(y in 2:ncol(TDM))
#   {
#     doc.tfidf[x,y] <- (doc.tfidf[x,y] / tf[y]) * idf[x]
#   }
# }

tempY = matrix(rep(c(as.matrix(tf)), each = length(idf)), nrow = length(idf))
tempX = matrix(rep(c(as.matrix(idf)), each = length(tf)), ncol = length(tf), byrow = TRUE)
doc.tfidf[,2:(n+1)] <- (doc.tfidf[,2:(n+1)] / tempY) * tempX

stopLine = rowSums(doc.tfidf[,2:(n+1)])
delID = which(stopLine == 0)

kable(head(doc.tfidf[delID,1]))
kable(tail(doc.tfidf[delID,1]))
TDM = TDM[-delID,]
doc.tfidf = doc.tfidf[-delID,]
```

-------------------------------------------------------------------------------------------------

## Key-Words
```{r}
TopWords = data.frame()
for( id in c(1:n) )
{
  dayMax = order(doc.tfidf[,id+1], decreasing = TRUE)
  showResult = t(as.data.frame(doc.tfidf[dayMax[1:5],1]))
  TopWords = rbind(TopWords, showResult)
}
rownames(TopWords) = colnames(doc.tfidf)[2:(n+1)]
TopWords = droplevels(TopWords)
kable(TopWords)
```

-------------------------------------------------------------------------------------------------

## TDM Merge to Visiualization
```{r}
TDM$d = as.character(TDM$d)
AllTop = as.data.frame( table(as.matrix(TopWords)) )
AllTop = AllTop[order(AllTop$Freq, decreasing = TRUE),]

kable(head(AllTop))
TopNo = 5
tempGraph = data.frame()
for( t in c(1:TopNo) )
{
  word = matrix( rep(c(as.matrix(AllTop$Var1[t])), each = n), nrow = n )
  temp = cbind( colnames(doc.tfidf)[2:(n+1)], t(TDM[which(TDM$d == AllTop$Var1[t]), 2:(n+1)]), word )
  colnames(temp) = c("date", "freq", "words")
  tempGraph = rbind(tempGraph, temp)
  names(tempGraph) = c("date", "freq", "words")
}


tempGraph$freq = unfactor(tempGraph$freq)
ggplot(tempGraph, aes(date, freq)) + 
  geom_point(aes(color = words, shape = words), size = 5) +
  geom_line(aes(group = words, linetype = words))
kable(tail(AllTop))
```
#### My Opinion:若依據7/19成績放榜日來看，討論度相當高的是北大，也許可以假設鄉民們的目標於此、或是成績可達北大分數；而放榜前一日，大家最關心的莫過於筱關分數的五標，先為自己初步分析落點

-------------------------------------------------------------------------------------------------

## See the Results
```{r}
filenames = as.array(paste0("./DATA/",colnames(doc.tfidf)[2:(n+1)],".txt"))
sizeResult = apply(filenames, 1, file.size) / 1024
showSize = data.frame(colnames(doc.tfidf)[2:(n+1)], sizeResult)
names(showSize) = c("date", "size_KB")

ggplot(showSize, aes(x = date, y = size_KB)) + geom_bar(fill="pink", color="white", stat="identity")
# Change colors for a good looking (LOL)
```
#### My Opinion:以這三天來說，成績放榜當天7/19討論為最熱烈，連20日也趕不上，可推測考生們相當積極於自己未來的去向

-------------------------------------------------------------------------------------------------

## TFIDF
```{r}
docs.corpus <- Corpus(DirSource("./DATA"))
docs.seg <- tm_map(docs.corpus, segmentCN)
docs.tdm <- TermDocumentMatrix(docs.seg)

docs.tf <- apply(as.matrix(docs.tdm), 2, function(word) { word/sum(word) })
idf <- function(doc) {
  return ( log2( length(doc)+1 / nnzero(doc)) )
}
docs.idf <- apply(as.matrix(docs.tdm), 1, idf)
docs.tfidf <- docs.tf * docs.idf
```

-------------------------------------------------------------------------------------------------

## PCA
```{r}
docs.pca <- prcomp(docs.tfidf, scale = T)

fviz_eig(docs.pca)
fviz_pca_ind(docs.pca, geom.ind = c("point"), col.ind = "cos2")
fviz_pca_var(docs.pca, col.var = "contrib")
fviz_pca_var(docs.pca, col.var = "contrib")
docs.eig <- get_eig(docs.pca)
docs.var <- get_pca_var(docs.pca)
docs.ind <- get_pca_ind(docs.pca)
```

-------------------------------------------------------------------------------------------------

# Kmeans
```{r}
ind.coord2 <- docs.ind$coord[, 1:2]
wss <- c()
for (i in 1:10) { wss[i] <- kmeans(ind.coord2, i)$tot.withinss }
plot(wss, type = "b")

km <- kmeans(ind.coord2, 3)
plot(ind.coord2, col = km$cluster)
points(km$centers, col = 1:3, pch = 8, cex = 2)
```
